[
  {
    "center": [
      0.5,
      0.905842
    ],
    "kind": "ud",
    "match": "start",
    "module": "gf9598",
    "project": [
      "pd2415"
    ],
    "shooter": 12,
    "size": [
      0.171262,
      0.07739
    ]
  },
  {
    "center": [
      0.5,
      0.903011
    ],
    "kind": "ud",
    "match": "start",
    "module": "gf9598",
    "project": [
      "pd2419"
    ],
    "shooter": 12,
    "size": [
      0.178776,
      0.082345
    ]
  }
]